version: 2
updates:
  # Python
  - package-ecosystem: "pip"
    directory: "./"
    target-branch: main
    schedule:
      interval: "weekly"
    assignees:
      - "jonasscholl"
    groups:
      python:
        patterns:
          - "*"

  # Node.js
  # - package-ecosystem: "npm"
  #   directory: "/app"
  #   target-branch: main
  #   schedule:
  #     interval: "weekly"
  #   assignees:
  #     - "jonasscholl"
  #   groups:
  #     app:
  #       patterns:
  #         - "*"
